POST http://127.0.0.1:8000/signup/ 
Content-Type: application/json

{ "username": "123", "password": "123", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "khja", "password": "123" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token 0ffea653a2b27ca50b32f132524e78aa76f5fb9d



###

POST http://127.0.0.1:8000/team/
Content-Type: application/json

    {
        "id_eq":4,
        "nom_eq": "non renseigné",
        "resp_eq": 88,
        "start_eq": "2023-09-04",
        "project_run": "L'équipe vient de débuter récemment",
        "emp_eq": [
            89, 90
        ]
    }



###

POST http://127.0.0.1:8000/employee/
Content-Type: application/json

{
    
    "nomComplet": "khadija ard",
    "email": "khadijaarradi01@gmail.com",
    "contact": "0616320616",
    "adresse": "sidi gf",
    "poste": "scrum master",
    "salaire": 100000.0,
    "statut_emploi": "stagiaire"
}
