# Generated by Django 4.2.4 on 2023-09-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('poste', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id_vac', models.AutoField(primary_key=True, serialize=False)),
                ('type_vac', models.CharField(max_length=200, null=True)),
                ('start_vac', models.DateField()),
                ('end_vac', models.DateField()),
                ('duration_vac', models.IntegerField()),
                ('reason_vac', models.CharField(max_length=200, null=True)),
                ('approbateur_vac', models.CharField(max_length=200)),
                ('id_emp_vac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id_trb', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('intitule_trb', models.CharField(max_length=200)),
                ('resp_trb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
            ],
        ),
    ]
