# Generated by Django 4.2.4 on 2023-09-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='resp_trb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='id_emp_vac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_eq', models.AutoField(primary_key=True, serialize=False)),
                ('nom_eq', models.CharField(default='non renseigné', max_length=200, null=True)),
                ('start_eq', models.DateField(default='non renseigné', max_length=200, null=True)),
                ('project_run', models.CharField(default="L'équipe vient de débuter récemment", max_length=200, null=True)),
                ('emp_eq', models.ManyToManyField(blank=True, related_name='equipes', to='main.employee')),
                ('resp_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
